jobs:
  stale:
    permissions:
      issues: write
      pull-requests: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/stale@v3
      with:
        exempt-issue-milestones: awaiting-approval,work-in-progress, discussion
        stale-issue-message: This issue has been automatically marked as stale because
          it has not had recent activity. It will be closed if no further activity
          occurs. Thank you for your contributions. You may also mark this issue as
          a "discussion" and i will leave this open
        stale-pr-message: This pull request has been marked as stale. Thank you for
          your contributions. You may also comment, or remove this label in order
          to avoid closing this.
name: Mark stale issues and pull requests
on:
  repository_dispatch:
    types: trigger-ga___stale.yml
